//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProjectSon.WebFormsUI.AdminPanel.UserControls {
    
    
    public partial class DashBoard {
        
        /// <summary>
        /// ltCountOfUnConfirmedUsers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltCountOfUnConfirmedUsers;
        
        /// <summary>
        /// ltCountOfUnConfirmedArticle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltCountOfUnConfirmedArticle;
    }
}
