//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProjectSon.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminMenu
    {
        public AdminMenu()
        {
            this.AdminMenu1 = new HashSet<AdminMenu>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string MenuIcon { get; set; }
        public string Link { get; set; }
        public Nullable<int> TopMenuId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<AdminMenu> AdminMenu1 { get; set; }
        public virtual AdminMenu AdminMenu2 { get; set; }
    }
}
