//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProjectSon.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public AdminUser()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Photo { get; set; }
        public string Job { get; set; }
        public Nullable<System.DateTime> MemberShipDate { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
    }
}
