//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProjectSon.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogEntry
    {
        public BlogEntry()
        {
            this.BlogEntryPhotoes = new HashSet<BlogEntryPhoto>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Abstract { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<BlogEntryPhoto> BlogEntryPhotoes { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
