//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProjectSon.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.BlogEntries = new HashSet<BlogEntry>();
        }
    
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> AdminUserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
        public virtual ICollection<BlogEntry> BlogEntries { get; set; }
    }
}
