//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProjectSon.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BlogEntries = new HashSet<BlogEntry>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsMailConfirmed { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Photo { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
    
        public virtual ICollection<BlogEntry> BlogEntries { get; set; }
    }
}
